export const trendingCardsTshirt = [
	{
		img: "/images/shirt.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/shirt.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/shirt.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/shirt.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/shirt.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/shirt.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/shirt.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/shirt.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/shirt.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
];
export const trendingCardsShoes = [
	{
		img: "/images/shoes.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/shoes.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/shoes.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/shoes.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/shoes.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/shoes.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/shoes.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/shoes.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/shoes.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
];
export const trendingCardsPant = [
	{
		img: "/images/pant.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/pant.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/pant.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/pant.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/pant.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/pant.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/pant.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/pant.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/pant.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
];
export const trendingCardsCaps = [
	{
		img: "/images/pant.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/pant.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/pant.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/pant.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/pant.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/pant.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/pant.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/pant.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
	{
		img: "/images/pant.png",
		title: "{MISSING_MODEL_TITLE}",
		artist: "{MISSING_ARTIST_NAME}",
		description: "{MISSING_MODEL_DESCRIPTION}",
		type: "Model Type",
	},
]
