/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./pant/pant.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pant.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials['SSC_Grey_Sweatpants.001']} position={[0, -0.156, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/pant.glb')
