/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./shoe/shoe.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/shoe.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rest_1.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.Rest_2.geometry} material={materials.PaletteMaterial001} />
    </group>
  )
}

useGLTF.preload('/shoe.glb')
