/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./shirt/tshirt.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tshirt.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tshirt.geometry} material={materials['FABRIC_1_FRONT_4193.001']} />
    </group>
  )
}

useGLTF.preload('/tshirt.glb')
